ADOPTABLE_PETS = [
    {
        "id": "PET-0001",
        "nombre": "Luna",
        "especie": "Perro",
        "raza": "Labrador Retriever",
        "edad": 2,
        "tamano": "mediano",
        "sexo": "Hembra",
        "ciudad": "Bogota",
        "departamento": "Cundinamarca",
        "descripcion": "Perra joven muy juguetona, sociable y carinosa con ninos y otros perros.",
        "foto_url": "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": True,
        "esterilizado": True,
        "adopcion_estado": "available",
        "peso_kg": 24.0,
        "peso_texto": "24 kg",
        "caracteristicas": ["Juguetona", "Sociable", "Vacunada"],
        "refugio": {
            "id": "SHELTER-BOG",
            "nombre": "Refugio Esperanza Bogota",
            "telefono": "+57 1 555 1234",
            "email": "contacto@esperanzabogota.org",
            "ciudad": "Bogota",
            "departamento": "Cundinamarca",
            "direccion": "Calle 123 #45-67, Bogota",
            "verificado": True,
        },
    },
    {
        "id": "PET-0002",
        "nombre": "Max",
        "especie": "Perro",
        "raza": "Pastor Aleman",
        "edad": 4,
        "tamano": "grande",
        "sexo": "Macho",
        "ciudad": "Medellin",
        "departamento": "Antioquia",
        "descripcion": "Guardian tranquilo y muy leal, disfruta las caminatas largas y es obediente.",
        "foto_url": "https://images.unsplash.com/photo-1557979619-445218f32648?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": True,
        "esterilizado": True,
        "adopcion_estado": "available",
        "peso_kg": 32.0,
        "peso_texto": "32 kg",
        "caracteristicas": ["Guardian", "Leal", "Obediente"],
        "refugio": {
            "id": "SHELTER-MDE",
            "nombre": "Refugio Amigo Fiel",
            "telefono": "+57 4 600 2020",
            "email": "hola@amigofiel.org",
            "ciudad": "Medellin",
            "departamento": "Antioquia",
            "direccion": "Carrera 45 #10-12, Medellin",
            "verificado": False,
        },
    },
    {
        "id": "PET-0003",
        "nombre": "Milo",
        "especie": "Gato",
        "raza": "Siames",
        "edad": 1,
        "tamano": "pequeno",
        "sexo": "Macho",
        "ciudad": "Cali",
        "departamento": "Valle del Cauca",
        "descripcion": "Gato activo, curioso y jugueton que ama las alturas y busca compania humana.",
        "foto_url": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": True,
        "esterilizado": False,
        "adopcion_estado": "available",
        "peso_kg": 4.2,
        "peso_texto": "4.2 kg",
        "caracteristicas": ["Curioso", "Activo", "Carinoso"],
        "refugio": {
            "id": "SHELTER-CALI",
            "nombre": "Fundacion Bigotes Felices",
            "telefono": "+57 2 300 4545",
            "email": "contacto@bigotesfelices.org",
            "ciudad": "Cali",
            "departamento": "Valle del Cauca",
            "direccion": "Av. Sexta 78-09, Cali",
            "verificado": True,
        },
    },
    {
        "id": "PET-0004",
        "nombre": "Canela",
        "especie": "Perro",
        "raza": "Beagle",
        "edad": 3,
        "tamano": "mediano",
        "sexo": "Hembra",
        "ciudad": "Barranquilla",
        "departamento": "Atlantico",
        "descripcion": "Muy amigable y sociable, disfruta jugar en el parque y seguir rastros.",
        "foto_url": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": True,
        "esterilizado": True,
        "adopcion_estado": "available",
        "peso_kg": 11.5,
        "peso_texto": "11.5 kg",
        "caracteristicas": ["Sociable", "Energetica", "Carinosa"],
        "refugio": {
            "id": "SHELTER-BAQ",
            "nombre": "Huellas del Atlantico",
            "telefono": "+57 5 400 8080",
            "email": "info@huellasdelatlantico.org",
            "ciudad": "Barranquilla",
            "departamento": "Atlantico",
            "direccion": "Calle 72 #43-21, Barranquilla",
            "verificado": True,
        },
    },
    {
        "id": "PET-0005",
        "nombre": "Nala",
        "especie": "Gato",
        "raza": "Angora Turco",
        "edad": 5,
        "tamano": "pequeno",
        "sexo": "Hembra",
        "ciudad": "Bucaramanga",
        "departamento": "Santander",
        "descripcion": "Gata tranquila y carinosa, ideal para hogares calmados, le encanta estar cerca.",
        "foto_url": "https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": True,
        "esterilizado": True,
        "adopcion_estado": "available",
        "peso_kg": 3.8,
        "peso_texto": "3.8 kg",
        "caracteristicas": ["Tranquila", "Carinosa", "Independiente"],
        "refugio": {
            "id": "SHELTER-BGA",
            "nombre": "Rescate Felino Santander",
            "telefono": "+57 7 785 1212",
            "email": "rescate@felinosantander.org",
            "ciudad": "Bucaramanga",
            "departamento": "Santander",
            "direccion": "Calle 37 #25-45, Bucaramanga",
            "verificado": False,
        },
    },
    {
        "id": "PET-0006",
        "nombre": "Rocky",
        "especie": "Perro",
        "raza": "Bulldog Ingles",
        "edad": 6,
        "tamano": "mediano",
        "sexo": "Macho",
        "ciudad": "Cartagena",
        "departamento": "Bolivar",
        "descripcion": "Carismatico y sociable, disfruta las siestas y la compania de la familia.",
        "foto_url": "https://images.unsplash.com/photo-1517842184082-909c9e316dda?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": False,
        "esterilizado": True,
        "adopcion_estado": "available",
        "peso_kg": 22.4,
        "peso_texto": "22.4 kg",
        "caracteristicas": ["Relajado", "Sociable", "Afectuoso"],
        "refugio": {
            "id": "SHELTER-CTG",
            "nombre": "Rescate Bulldog Cartagena",
            "telefono": "+57 5 600 1111",
            "email": "contacto@bulldogctg.org",
            "ciudad": "Cartagena",
            "departamento": "Bolivar",
            "direccion": "Calle 30 #15-44, Cartagena",
            "verificado": False,
        },
    },
    {
        "id": "PET-0007",
        "nombre": "Toby",
        "especie": "Perro",
        "raza": "Criollo",
        "edad": 2,
        "tamano": "mediano",
        "sexo": "Macho",
        "ciudad": "Manizales",
        "departamento": "Caldas",
        "descripcion": "Muy activo y jugueton, perfecto para familias aventureras y con ninos.",
        "foto_url": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": True,
        "esterilizado": False,
        "adopcion_estado": "available",
        "peso_kg": 18.0,
        "peso_texto": "18 kg",
        "caracteristicas": ["Energetico", "Jugueton", "Fiel"],
        "refugio": {
            "id": "SHELTER-MZL",
            "nombre": "Patas Felices Manizales",
            "telefono": "+57 6 777 9090",
            "email": "hola@patasfelices.org",
            "ciudad": "Manizales",
            "departamento": "Caldas",
            "direccion": "Carrera 12 #8-55, Manizales",
            "verificado": True,
        },
    },
    {
        "id": "PET-0008",
        "nombre": "Kiara",
        "especie": "Gato",
        "raza": "Bengali",
        "edad": 3,
        "tamano": "pequeno",
        "sexo": "Hembra",
        "ciudad": "Pereira",
        "departamento": "Risaralda",
        "descripcion": "Gata curiosa, amorosa y sociable, convive bien con otros gatos y perros.",
        "foto_url": "https://images.unsplash.com/photo-1516375199440-1685b2d5bbf3?auto=format&fit=crop&w=400&q=80",
        "vacunas_al_dia": True,
        "esterilizado": True,
        "adopcion_estado": "available",
        "peso_kg": 4.5,
        "peso_texto": "4.5 kg",
        "caracteristicas": ["Curiosa", "Afectuosa", "Adaptable"],
        "refugio": {
            "id": "SHELTER-PER",
            "nombre": "Refugio Bigotes Pereira",
            "telefono": "+57 6 555 3030",
            "email": "adopciones@bigotespereira.org",
            "ciudad": "Pereira",
            "departamento": "Risaralda",
            "direccion": "Carrera 7 #21-30, Pereira",
            "verificado": True,
        },
    },
]
